#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar height=37        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=15  \
                 padding_right=15 \
                 y_offset=2       \
                 color=$BAR_COLOR

# Add aerospace workspace change event first
sketchybar --add event aerospace_workspace_change

##### Changing Defaults #####
sketchybar --default icon.font="SF Pro:Semibold:15.0"  \
                     icon.color=$WHITE                 \
                     label.font="SF Pro:Semibold:15.0" \
                     label.color=$WHITE                \
                     background.color=$ITEM_BG_COLOR       \
                     background.corner_radius=5            \
                     background.height=24                  \
                     padding_left=3                        \
                     padding_right=3                       \
                     label.padding_left=4                  \
                     label.padding_right=8                 \
                     icon.padding_left=8                   \
                     icon.padding_right=4

# -- Left Side Items --
source $ITEM_DIR/workspaces.sh
source $ITEM_DIR/front_app.sh

# -- Right Side Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

# -- Right Side Of Notch Items --
source $ITEM_DIR/media.sh

##### Finalizing Setup #####
sketchybar --update
