#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar height=37        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 color=$BAR_COLOR

##### Changing Defaults #####
sketchybar --default icon.font="SF Pro:Semibold:15.0"  \
                     icon.color=0xffffffff                 \
                     label.font="SF Pro:Semibold:15.0" \
                     label.color=0xffffffff                \
                     background.drawing=off                    \
                     background.color=$ITEM_BG_COLOR       \
                     background.corner_radius=5            \
                     background.height=24                  \
                     padding_left=5                        \
                     padding_right=5                       \
                     label.padding_left=4                  \
                     label.padding_right=4                 \
                     icon.padding_left=4                   \
                     icon.padding_right=4

##### Adding Left Items #####
source $ITEM_DIR/apple_logo.sh
source $ITEM_DIR/front_app.sh

##### Adding Right Items #####
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/dnd.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/ram.sh
source $ITEM_DIR/disk.sh
source $ITEM_DIR/volume.sh

##### Finalizing Setup #####
sketchybar --update
